version: '3'
services:
  server:
    image: iuriinedostup/multi-server:latest
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PG_USER
      - PGHOST=$PG_HOST
      - PGDATABASE=$PG_NAME
      - PGPASSWORD=$PG_PASS
      - PGPORT=$PG_PORT

  client:
    image: iuriinedostup/multi-client:latest
    stdin_open: true
    mem_limit: 128m
    hostname: client

  worker:
    image: iuriinedostup/multi-worker:latest
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT

  nginx:
    image: iuriinedostup/multi-nginx:latest
    mem_limit: 128m
    hostname: nginx
    ports:
    - 80:80